name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --only=production
    
    - name: Install test tools
      run: |
        npm install -g eslint
        npm install --save-dev jest supertest 

    - name: Run linting
      run: eslint app/ test/

    - name: Run tests
      run: jest --passWithNoTests
      env:
        NODE_ENV: test

    - name: Build Docker image
      run: |
          docker build -t my-node-app:ci-${{ github.sha }} .

  security-scan:
    runs-on: ubuntu-latest
    needs: test-and-lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image for security scan
      run: docker build -t my-node-app:security-scan .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-node-app:security-scan'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'